#ifndef RECOIL_VC5_CABOUT_PCH_CURRENT_STDAFX_H
#define RECOIL_VC5_CABOUT_PCH_CURRENT_STDAFX_H

#define RECOIL_MFC42_DELAY_AFXWIN_INLINES
#include "recoil/Mfc42Abi.h"
#undef RECOIL_MFC42_DELAY_AFXWIN_INLINES

#endif
